# Generated by Django 3.1 on 2020-09-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('follower', 'following')},
        ),
    ]
