# Generated by Django 3.1 on 2020-09-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('like_author', 'liked_post')},
        ),
    ]
